version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "hiring-agent-aws"
s3_prefix = "hiring-agent-aws"
region = "ap-south-1"
image_repositories = []

[default.local_start_api.parameters]
port = 3001
host = "127.0.0.1"
