// app/company/reports/page.tsx
'use client';

import CompanyNav from '@/components/CompanyNav';
import Breadcrumbs from '@/components/Breadcrumbs';
import { mockCandidateReports } from '@/data/mockData';
import { useState } from 'react';
import Link from 'next/link';
import { FileBarChart2, ArrowRight, CheckCircle2, Search, Filter } from 'lucide-react';
import CandidateDrawer from '@/components/CandidateDrawer';

export default function ReportsPage() {
  const [statusFilter, setStatusFilter] = useState('ALL');
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedReport, setSelectedReport] = useState<any | null>(null);

  const filteredReports = mockCandidateReports.filter((rep) => {
    const matchesSearch =
      rep.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      rep.role.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesSearch;
  });

  return (
    <div className="min-h-screen bg-black text-white font-sans">
      <CompanyNav />

      <main className="max-w-7xl mx-auto px-6 py-10">
        <Breadcrumbs items={[{ label: 'REPORTS' }]} />

        {/* Header */}
        <div className="border-b border-white/15 pb-8 mb-10 flex flex-col md:flex-row md:items-end justify-between gap-6 font-mono">
          <div>
            <span className="text-xs text-primary uppercase tracking-widest block mb-2 font-bold">
              // Candidate Intelligence Repository
            </span>
            <h1 className="font-bold text-4xl md:text-6xl tracking-tighter uppercase font-sans">
              REPORTS
            </h1>
            <p className="text-white/60 text-sm mt-1 font-mono">
              Compiled evidence reports generated by automated verification agents.
            </p>
          </div>

          <div className="text-xs text-white/50">
            TOTAL REPORTS: <span className="text-primary font-bold">{filteredReports.length}</span>
          </div>
        </div>

        {/* Filter & Search */}
        <div className="flex flex-col sm:flex-row gap-4 mb-10 font-mono text-xs">
          <div className="relative flex-1">
            <Search className="w-4 h-4 text-white/40 absolute left-4 top-3.5" />
            <input
              type="text"
              placeholder="Search candidate report or role..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full bg-white/[0.03] border border-white/20 pl-11 pr-4 py-3 text-white placeholder-white/40 focus:outline-none focus:border-primary transition"
            />
          </div>

          <div className="flex gap-2 shrink-0">
            {['ALL', 'READY', 'PROCESSING', 'NEEDS REVIEW'].map((st) => (
              <button
                key={st}
                onClick={() => setStatusFilter(st)}
                className={`px-4 py-3 border transition-colors ${
                  statusFilter === st
                    ? 'border-primary text-primary bg-primary/10 font-bold'
                    : 'border-white/20 text-white/60 hover:border-white/40'
                }`}
              >
                {st}
              </button>
            ))}
          </div>
        </div>

        {/* Data Table */}
        <div className="border border-white/15 bg-black font-mono text-xs">
          <div className="grid grid-cols-12 gap-4 p-4 border-b border-white/15 bg-white/[0.03] text-white/40 font-bold uppercase text-[10px]">
            <div className="col-span-4">CANDIDATE</div>
            <div className="col-span-3">ROLE REQUISITION</div>
            <div className="col-span-2">GENERATED</div>
            <div className="col-span-1">COVERAGE</div>
            <div className="col-span-2 text-right">ACTION</div>
          </div>

          <div className="divide-y divide-white/10">
            {filteredReports.map((report) => (
              <div
                key={report.id}
                onClick={() => setSelectedReport(report)}
                className="grid grid-cols-12 gap-4 p-4 items-center hover:bg-white/[0.03] transition-colors cursor-pointer group"
              >
                <div className="col-span-4">
                  <div className="font-bold text-sm text-white group-hover:text-primary transition-colors font-sans">
                    {report.name}
                  </div>
                  <div className="text-[10px] text-white/40">REPORT ID: {report.id}</div>
                </div>

                <div className="col-span-3 font-sans">
                  <div className="font-bold text-white text-xs">{report.role}</div>
                </div>

                <div className="col-span-2 text-white/70">
                  {report.appliedDate}
                </div>

                <div className="col-span-1 font-bold text-emerald-400">
                  {report.evidenceCoverage}%
                </div>

                <div className="col-span-2 text-right">
                  <Link
                    href={`/company/candidates/${report.id}`}
                    className="text-xs text-primary font-bold hover:underline inline-flex items-center gap-1"
                  >
                    VIEW REPORT →
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>

      <CandidateDrawer
        candidate={selectedReport}
        isOpen={!!selectedReport}
        onClose={() => setSelectedReport(null)}
      />
    </div>
  );
}
