'use client';

import { useEffect, useState, useCallback } from 'react';
import Link from 'next/link';
import { Search, Loader2 } from 'lucide-react';
import { CompanyNav, Breadcrumbs } from '@/components/layout';
import ApiErrorBanner from '@/components/layout/ApiErrorBanner';
import { CandidateAgentDrawer } from '@/components/company';
import { CandidateReport } from '@/data/mockData';
import { fetchApplications, ApiError } from '@/data/apiClient';
import { mapApplicationToCandidateReport } from '@/data/schemaAdapter';

export default function ReportsPage() {
  const [statusFilter, setStatusFilter] = useState('ALL');
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedReport, setSelectedReport] = useState<any | null>(null);
  const [reports, setReports] = useState<CandidateReport[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [apiError, setApiError] = useState<ApiError | string | null>(null);

  const loadReports = useCallback(async () => {
    setIsLoading(true);
    setApiError(null);
    try {
      const items = await fetchApplications();
      setReports(items.map(mapApplicationToCandidateReport));
    } catch (e: any) {
      setApiError(e instanceof ApiError ? e : (e?.message || 'Failed to load intelligence reports'));
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    loadReports();
  }, [loadReports]);

  const filteredReports = reports.filter((rep) => {
    const matchesSearch =
      rep.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      rep.role.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesSearch;
  });

  return (
    <div className="min-h-screen bg-black text-white font-sans">
      <CompanyNav />

      <main className="max-w-7xl mx-auto px-6 py-10">
        <Breadcrumbs items={[{ label: 'REPORTS' }]} />

        <div className="border-b border-white/15 pb-8 mb-10 flex flex-col md:flex-row md:items-end justify-between gap-6 font-mono">
          <div>
            <span className="text-xs text-primary uppercase tracking-widest block mb-2 font-bold">
              // Candidate Intelligence Repository
            </span>
            <h1 className="font-bold text-4xl md:text-6xl tracking-tighter uppercase font-sans">
              REPORTS
            </h1>
            <p className="text-white/60 text-sm mt-1 font-mono">
              Compiled evidence reports generated by automated verification agents.
            </p>
          </div>

          <div className="text-xs text-white/50">
            TOTAL REPORTS: <span className="text-primary font-bold">{filteredReports.length}</span>
          </div>
        </div>

        <div className="flex flex-col sm:flex-row gap-4 mb-10 font-mono text-xs">
          <div className="relative flex-1">
            <Search className="w-4 h-4 text-white/40 absolute left-4 top-3.5" />
            <input
              type="text"
              placeholder="Search candidate report or role..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full bg-white/[0.03] border border-white/20 pl-11 pr-4 py-3 text-white placeholder-white/40 focus:outline-none focus:border-primary transition"
            />
          </div>

          <div className="flex gap-2 shrink-0">
            {['ALL', 'READY', 'PROCESSING', 'NEEDS REVIEW'].map((st) => (
              <button
                key={st}
                onClick={() => setStatusFilter(st)}
                className={`px-4 py-3 border transition-colors ${
                  statusFilter === st
                    ? 'border-primary text-primary bg-primary/10 font-bold'
                    : 'border-white/20 text-white/60 hover:border-white/40'
                }`}
              >
                {st}
              </button>
            ))}
          </div>
        </div>

        <ApiErrorBanner
          error={apiError}
          onRetry={loadReports}
          title="Intelligence Reports Synchronization Failed"
          className="mb-8"
        />

        {isLoading ? (
          <div className="p-16 text-center font-mono flex flex-col items-center justify-center">
            <Loader2 className="w-8 h-8 text-primary animate-spin mb-4" />
            <span className="text-white/50 text-xs">Loading Candidate Intelligence Reports...</span>
          </div>
        ) : filteredReports.length === 0 ? (
          <div className="border border-dashed border-white/20 p-12 text-center font-mono">
            <div className="text-primary text-xs font-bold uppercase mb-2">
              {apiError ? '// CLOUD REPOSITORY ERROR' : '// INTELLIGENCE REPOSITORY EMPTY'}
            </div>
            <h3 className="text-lg font-bold text-white mb-2">
              {apiError ? 'FAILED TO RETRIEVE REPORTS' : 'NO CANDIDATE REPORTS GENERATED YET'}
            </h3>
            <p className="text-white/50 text-xs max-w-md mx-auto mb-6">
              {apiError
                ? 'Could not connect to the reports registry. Please ensure API Gateway is operational and retry.'
                : 'When candidates submit code repositories, automated evaluations produce deep intelligence reports and evidence graphs which will be cataloged here.'}
            </p>
            <Link
              href="/company/roles"
              className="px-6 py-3 bg-white text-black font-bold text-xs uppercase hover:bg-primary transition inline-flex items-center gap-2"
            >
              View Roles & Postings
            </Link>
          </div>
        ) : (
          <div className="border border-white/15 bg-black font-mono text-xs">
            <div className="grid grid-cols-12 gap-4 p-4 border-b border-white/15 bg-white/[0.03] text-white/40 font-bold uppercase text-[10px]">
              <div className="col-span-4">CANDIDATE</div>
              <div className="col-span-3">ROLE REQUISITION</div>
              <div className="col-span-2">GENERATED</div>
              <div className="col-span-1">COVERAGE</div>
              <div className="col-span-2 text-right">ACTION</div>
            </div>

            <div className="divide-y divide-white/10">
              {filteredReports.map((report) => (
                <div
                  key={report.id}
                  onClick={() => setSelectedReport(report)}
                  className="grid grid-cols-12 gap-4 p-4 items-center hover:bg-white/[0.03] transition-colors cursor-pointer group"
                >
                  <div className="col-span-4">
                    <div className="font-bold text-sm text-white group-hover:text-primary transition-colors font-sans">
                      {report.name}
                    </div>
                    <div className="text-[10px] text-white/40">REPORT ID: {report.id}</div>
                  </div>

                  <div className="col-span-3 font-sans">
                    <div className="font-bold text-white text-xs">{report.role}</div>
                  </div>

                  <div className="col-span-2 text-white/70">
                    {report.appliedDate}
                  </div>

                  <div className="col-span-1 font-bold text-emerald-400 text-[10px] uppercase">
                    Markdown ready
                  </div>

                  <div className="col-span-2 text-right">
                    <Link
                      href={`/company/candidates/${report.id}`}
                      className="text-xs text-primary font-bold hover:underline inline-flex items-center gap-1"
                    >
                      VIEW REPORT →
                    </Link>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </main>

      <CandidateAgentDrawer
        candidate={selectedReport}
        isOpen={!!selectedReport}
        onClose={() => setSelectedReport(null)}
      />
    </div>
  );
}
